#!/usr/bin/env bash
# shellcheck disable=SC1090
source "$(dirname "$(readlink -e -- "$0")")/core.source"

VERSION="${1:-1.0.1}"
TARGET="/usr/local/bin/act"
KERNEL="$(uname -s)"
HARDWARE="$(uname -m)"

if [[ "${KERNEL}" == "Linux" ]]; then
  ARCHITECTURE="$(dpkg --print-architecture)"
else
  >&2 echo ":: unsupported kernel"
fi

wget -q 'https://github.com/nektos/act/releases/download/v0.2.25/act_Linux_x86_64.tar.gz'
tar xzf act_Linux_x86_64.tar.gz
sudo mv "act" "${TARGET}"
